### ISSUE TITLE
Sources of Physical Randomness

### ISSUE THREAD

**Issue by gdbelvin** [gdbelvin/PrivText#1]
The API needs a library for sampling microphone, camera, bluethooth and other physical noise to seed the random number generator.

**Comment by jakinyele** [comment]
Openssl RNG good enough. May use TPM RNG (if available) as another source of randomness in the future.

**Comment by gdbelvin** [comment]
Do you know if openssl is available on smart phones?

On Sun, Dec 18, 2011 at 10:25 PM, J Ayo Akinyele <
reply@reply.github.com

**Comment by jakinyele** [comment]
Oops! I actually thought this was a Charm issue. My apologies! If you're referring to iOS, I believe you can incorporate the openssl library easily into your mobile app. But I'm also sure there are ways of doing the same thing on Android as well. Hope this helps!
